base:
  data_path: /Users/camille/apriorics_data
  ihc_type: AE1AE3
  mapping_file: ../../ihc_mapping.json
  mask_extension: .tif
  remote_path: /Volumes/AprioricsSlides
  slide_extension: .svs

local:
  mask_path: masks
  slide_path: slides
  wkt_path: wkts
  geojson_path: geojsons

remote:
  mask_path: masks
  slide_path: .
  wkt_path: wkts
  geojson_path: geojsons

slide_download:
  clean_previous: true
  import_ihc: true
  add_tree: true

mask_extraction:
  dab_thr: 0.03
  object_min_size: 1000
  binary_op: closing
  radius: 10
